# Site settings
title: My jorney to Data Science
email: avbrazhenko@gmail.com
description: "All about data... Blog about my journey in Data Analysis | Alex Brazhenko"
baseurl: "/"
github_username:  alexbra
permalink: /:year/:month/:day/:title/
relative_permalinks: true
# Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
